name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore tsol.slnx
    - name: Build
      run: dotnet build tsol.slnx --no-restore
    - name: Test
      run: dotnet test tsol.slnx --no-build --verbosity normal
